version: "3.8"

services:
  # Frontend service using Bun - Production
  client:
    image: ${REGISTRY}/kearney/client:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kearney-network

  # Backend service using Python/FastAPI - Production
  server:
    image: ${REGISTRY}/kearney/server:latest
    ports:
      - "8000:8000"
    volumes:
      - ./server/data:/app/data
    env_file:
      - ./server/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kearney-network

networks:
  kearney-network:
    driver: bridge

volumes:
  data:
