version: "3.8"

services:
  # Frontend service using Bun
  client:
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/styles:/app/styles
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  # Backend service using Python/FastAPI
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app/app
      - ./server/data:/app/data
    env_file:
      - ./server/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
